title: Bea De Oliveira
google_scholar: https://scholar.google.com/
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/in/beatriz-de-oliveira-3489a812a/
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
logo: webpic-modified.png
theme: jekyll-theme-minimal
