title: Bea De Oliveira
linkedin: https://www.linkedin.com/in/beatriz-de-oliveira-3489a812a/
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
logo: current_headshot.png
theme: jekyll-theme-minimal
